// List of 100 adjectives (all in lowercase)
const adjectives: string[] = [
  'happy',
  'brave',
  'dashing',
  'playful',
  'clever',
  'energetic',
  'witty',
  'graceful',
  'spunky',
  'wise',
  'charming',
  'gentle',
  'jovial',
  'lively',
  'fearless',
  'silly',
  'calm',
  'quirky',
  'eager',
  'zealous',
  'honest',
  'zesty',
  'quirky',
  'sincere',
  'kind',
  'thoughtful',
  'loyal',
  'fierce',
  'generous',
  'relaxed',
  'elegant',
  'silly',
  'bold',
  'friendly',
  'clever',
  'sensitive',
  'cheerful',
  'gentle',
  'patient',
  'helpful',
  'cozy',
  'funny',
  'happy',
  'jolly',
  'merry',
  'playful',
  'bright',
  'sunny',
  'cool',
  'curious',
  'romantic',
  'silly',
  'witty',
  'joyful',
  'friendly',
  'gracious',
  'lovely',
  'peaceful',
  'polite',
  'blissful',
  'sincere',
  'courageous',
  'eager',
  'fearless',
  'glorious',
  'hopeful',
  'innocent',
  'determined',
  'humble',
  'faithful',
  'modest',
  'loyal',
  'kind',
  'thoughtful',
  'optimistic',
  'patient',
  'proud',
  'vibrant',
  'wonderful',
  'sincere',
  'clever',
  'caring',
  'graceful',
  'brave',
  'courageous',
  'grateful',
  'honest',
  'romantic',
  'gentle',
  'compassionate',
  'elegant',
  'upbeat',
  'happy',
  'dreamy',
  'whimsical',
  'playful',
  'daring',
  'sparkling',
];

// List of 100 animals (all in lowercase)
const animals: string[] = [
  'panda',
  'eagle',
  'cheetah',
  'otter',
  'fox',
  'gazelle',
  'owl',
  'dolphin',
  'kangaroo',
  'turtle',
  'lion',
  'tiger',
  'elephant',
  'zebra',
  'monkey',
  'giraffe',
  'penguin',
  'leopard',
  'koala',
  'jaguar',
  'squirrel',
  'rhino',
  'seahorse',
  'hippo',
  'hedgehog',
  'crocodile',
  'whale',
  'zebu',
  'wombat',
  'ibex',
  'chameleon',
  'bison',
  'lynx',
  'otter',
  'pangolin',
  'quetzal',
  'raccoon',
  'tapir',
  'vulture',
  'weasel',
  'xenops',
  'yak',
  'zebrafish',
  'marmoset',
  'newt',
  'ostrich',
  'parrot',
  'quokka',
  'raven',
  'sheep',
  'toucan',
  'uakari',
  'viper',
  'wombat',
  'x-raytetra',
  'yak',
  'zebu',
  'alpaca',
  'bison',
  'cougar',
  'dolphin',
  'elephant',
  'ferret',
  'giraffe',
  'hippo',
  'ibis',
  'jaguar',
  'koala',
  'lemur',
  'moose',
  'narwhal',
  'ocelot',
  'platypus',
  'quetzal',
  'reindeer',
  'sloth',
  'tapir',
  'unicorn',
  'vampirebat',
  'whale',
  'x-raytetra',
  'yak',
  'zebra',
];

// List of 100 flowers (all in lowercase)
const flowers: string[] = [
  'rose',
  'lily',
  'tulip',
  'daisy',
  'sunflower',
  'orchid',
  'hydrangea',
  'iris',
  'carnation',
  'poppy',
  'daffodil',
  'chrysanthemum',
  'peony',
  'lilac',
  'violet',
  'marigold',
  'gerbera',
  'snapdragon',
  'zinnia',
  'anemone',
  'aster',
  'bluebell',
  'crocus',
  'delphinium',
  'freesia',
  'gladiolus',
  'hibiscus',
  'impatiens',
  'jasmine',
  'kalanchoe',
  'lavender',
  'magnolia',
  'narcissus',
  'orchid',
  'pansy',
  'queenanneslace',
  'ranunculus',
  'snapdragon',
  'tulip',
  'universalmorningglory',
  'violet',
  'wisteria',
  'xeranthemum',
  'yarrow',
  'zinnia',
  'alstroemeria',
  'begonia',
  'crocus',
  'daffodil',
  'eustoma',
  'freesia',
  'gladiolus',
  'heliconia',
  'iris',
  'jonquil',
  'kalanchoe',
  'larkspur',
  'magnolia',
  'narcissus',
  'orchid',
  'pansy',
  'queenanneslace',
  'ranunculus',
  'starofbethlehem',
  'tulip',
  'utricularia',
  'viola',
  'waxflower',
  'xeranthemum',
  'yarrow',
  'zinnia',
];

// List of 100 colors (all in lowercase)
const colors: string[] = [
  'white',
  'black',
  'gray',
  'red',
  'green',
  'blue',
  'yellow',
  'orange',
  'pink',
  'purple',
  'brown',
  'beige',
  'navy',
  'teal',
  'cyan',
  'magenta',
  'turquoise',
  'lavender',
  'maroon',
  'olive',
  'gold',
  'silver',
  'indigo',
  'coral',
  'salmon',
  'charcoal',
  'plum',
  'ruby',
  'emerald',
  'sapphire',
  'amber',
  'ivory',
  'mauve',
  'fuchsia',
  'lilac',
  'coral',
  'aqua',
  'mint',
  'forest',
  'periwinkle',
  'peach',
  'sky blue',
  'pumpkin',
  'chocolate',
  'khaki',
  'burgundy',
  'moss green',
  'mustard',
  'orchid',
  'steel blue',
  'lemon',
  'eggplant',
  'turmeric',
  'ruby red',
  'dusty rose',
  'tangerine',
  'olive green',
  'teal blue',
  'navy blue',
  'sunflower yellow',
  'baby pink',
  'deep purple',
  'dark brown',
  'pastel green',
  'light blue',
  'brick red',
  'coral pink',
  'mint green',
  'charcoal gray',
  'lavender purple',
  'dusty blue',
  'salmon pink',
  'lilac purple',
  'caramel',
  'apricot',
  'forest green',
  'pale yellow',
  'light gray',
  'rose gold',
  'aqua blue',
  'mauve pink',
  'peachy pink',
  'burgundy red',
  'turquoise blue',
  'pearl white',
  'ash gray',
  'ruby red',
  'emerald green',
  'sapphire blue',
  'coral orange',
  'ocean blue',
  'plum purple',
  'amethyst purple',
  'topaz yellow',
  'olive brown',
  'pumpkin orange',
  'lavender blue',
  'steel gray',
  'maroon red',
  'indigo blue',
];

// List of 100 vehicles (all in lowercase)
const vehicles: string[] = [
  'car',
  'truck',
  'motorcycle',
  'bicycle',
  'van',
  'bus',
  'suv',
  'train',
  'tram',
  'helicopter',
  'airplane',
  'boat',
  'jet ski',
  'yacht',
  'scooter',
  'moped',
  'segway',
  'skateboard',
  'rickshaw',
  'golf cart',
  'hot air balloon',
  'zeppelin',
  'submarine',
  'jetpack',
  'motorhome',
  'skate cycle',
  'hang glider',
  'unicycle',
  'kayak',
  'canoe',
  'go-kart',
  'bulldozer',
  'crane',
  'forklift',
  'excavator',
  'snowmobile',
  'hovercraft',
  'jet boat',
  'amphibious vehicle',
  'submersible',
  'parachute',
  'jet surfboard',
  'segway scooter',
  'trolleybus',
  'seaplane',
  'motorized wheelchair',
  'speedboat',
  'riverboat',
  'police car',
  'fire truck',
  'ambulance',
  'racing car',
  'convertible',
  'limousine',
  'rv (recreational vehicle)',
  'tow truck',
  'ice cream truck',
  'school bus',
  'dump truck',
  'garbage truck',
  'bulldozer',
  'crane truck',
  'cement mixer',
  'mail truck',
  'tractor',
  'snowplow',
  'bicycle taxi (bicitaxi)',
  'rickshaw',
  'electric scooter',
  'horse carriage',
  'cable car',
  'bullet train',
  'steam locomotive',
  'monorail',
  'maglev train',
  'electric bus',
  'air ambulance',
  'cargo plane',
  'fighter jet',
  'biplane',
  'hang glider',
  'airship',
  'hydroplane',
  'catamaran',
  'sailboat',
  'tugboat',
  'jet ski',
  'submarine',
  'amphibious vehicle',
  'hot air balloon',
  'glider',
  'rv (recreational vehicle)',
  'motorized wheelchair',
  'electric skateboard',
  'electric scooter',
  'electric bike',
  'segway',
  'skate cycle',
  'segway scooter',
  'hoverboard',
];

// List of 100 trees (all in lowercase)
const trees: string[] = [
  'oak',
  'pine',
  'maple',
  'birch',
  'willow',
  'cedar',
  'spruce',
  'ash',
  'cypress',
  'hickory',
  'mahogany',
  'cherry',
  'redwood',
  'poplar',
  'elm',
  'cottonwood',
  'alder',
  'beech',
  'chestnut',
  'hazel',
  'walnut',
  'sycamore',
  'sandalwood',
  'teak',
  'ebony',
  'rosewood',
  'baobab',
  'banyan',
  'cork oak',
  'buckeye',
  'bottlebrush',
  'cacao',
  'catalpa',
  'cinnamomum',
  'clove',
  'coconut palm',
  'cornelian cherry',
  'dragon tree',
  'eucalyptus',
  'fig',
  'ginkgo',
  'honey locust',
  'ironwood',
  'jackfruit',
  'kapok',
  'katsura',
  'laburnum',
  'magnolia',
  'mango',
  'northern catalpa',
  'osage orange',
  'papaya',
  'persimmon',
  'pistachio',
  'red mulberry',
  'redbud',
  'sassafras',
  'serviceberry',
  'silver birch',
  'silver linden',
  'sugar maple',
  'sweetgum',
  'tulip tree',
  'wattle',
  'white mulberry',
  'yellowwood',
  'zamia',
  'aleppo pine',
  'arborvitae',
  'balsam fir',
  'black locust',
  'carob',
  'cedar of lebanon',
  'douglas fir',
  'english oak',
  'european beech',
  'fraser fir',
  'goji berry',
  'goldenchain tree',
  'hazelnut',
  'holly',
  'ironbark',
  'japanes cedar',
  'kousa dogwood',
  'larch',
  'lemon tree',
  'lime tree',
  'lychee tree',
  'madrone',
  'mountain ash',
  'nance tree',
  'new zealand christmas tree',
  'oak tree',
  'pawpaw',
  'peach tree',
  'quaking aspen',
  'red cherry',
  'rowan',
  'sassafras tree',
  'service tree',
  'silver birch',
  'sweet birch',
  'tamarind tree',
  'thuja',
  'umbrella tree',
  'vanilla planifolia',
  'wax myrtle',
  'whitebeam',
  'yellow birch',
  'zelkova',
];

export { adjectives, animals, colors, flowers, trees, vehicles };
